server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

inference:
  concurrency:
    maxConcurrent: 8
    workerThreads: 8
    queueCapacity: 200
    acquireTimeoutMs: 50

